name=input("Enter your name:")
profession=input("Enter your favourite profession:")
noun=input("Enter any noun:")
print(f"My name is {name}, i am a great {profession}")
print(f"My target is to become the greatest {profession}")
print(f"During my journey i want to have many {noun}")